package app.model;
// Generated Jul 4, 2018 8:41:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Escuela generated by hbm2java
 */
public class Escuela  implements java.io.Serializable {


     private Integer idEscuela;
     private String nivel;
     private String grado;
     private String grupo;
     private Set personas = new HashSet(0);

    public Escuela() {
    }

    public Escuela(String nivel, String grado, String grupo, Set personas) {
       this.nivel = nivel;
       this.grado = grado;
       this.grupo = grupo;
       this.personas = personas;
    }
   
    public Integer getIdEscuela() {
        return this.idEscuela;
    }
    
    public void setIdEscuela(Integer idEscuela) {
        this.idEscuela = idEscuela;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


