package app.model;
// Generated Jul 4, 2018 8:41:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private String nombre;
     private String encargado;
     private Set personas = new HashSet(0);

    public Grupo() {
    }

    public Grupo(String nombre, String encargado, Set personas) {
       this.nombre = nombre;
       this.encargado = encargado;
       this.personas = personas;
    }
   
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEncargado() {
        return this.encargado;
    }
    
    public void setEncargado(String encargado) {
        this.encargado = encargado;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


