package app.model;
// Generated Jul 4, 2018 8:41:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Iglesia generated by hbm2java
 */
public class Iglesia  implements java.io.Serializable {


     private Integer idIglesia;
     private Direccion direccion;
     private String nombre;
     private String clave;
     private Set personas = new HashSet(0);

    public Iglesia() {
    }

    public Iglesia(Direccion direccion, String nombre, String clave, Set personas) {
       this.direccion = direccion;
       this.nombre = nombre;
       this.clave = clave;
       this.personas = personas;
    }
   
    public Integer getIdIglesia() {
        return this.idIglesia;
    }
    
    public void setIdIglesia(Integer idIglesia) {
        this.idIglesia = idIglesia;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


