package app.model;
// Generated Jul 4, 2018 8:41:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private Integer idServicio;
     private String agua;
     private String telefono;
     private String luz;
     private String gas;
     private String internet;
     private String cable;
     private Set viviendas = new HashSet(0);

    public Servicio() {
    }

    public Servicio(String agua, String telefono, String luz, String gas, String internet, String cable, Set viviendas) {
       this.agua = agua;
       this.telefono = telefono;
       this.luz = luz;
       this.gas = gas;
       this.internet = internet;
       this.cable = cable;
       this.viviendas = viviendas;
    }
   
    public Integer getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }
    public String getAgua() {
        return this.agua;
    }
    
    public void setAgua(String agua) {
        this.agua = agua;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getLuz() {
        return this.luz;
    }
    
    public void setLuz(String luz) {
        this.luz = luz;
    }
    public String getGas() {
        return this.gas;
    }
    
    public void setGas(String gas) {
        this.gas = gas;
    }
    public String getInternet() {
        return this.internet;
    }
    
    public void setInternet(String internet) {
        this.internet = internet;
    }
    public String getCable() {
        return this.cable;
    }
    
    public void setCable(String cable) {
        this.cable = cable;
    }
    public Set getViviendas() {
        return this.viviendas;
    }
    
    public void setViviendas(Set viviendas) {
        this.viviendas = viviendas;
    }




}


