package app.model;
// Generated Jul 4, 2018 8:41:06 PM by Hibernate Tools 4.3.1



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer userRoleId;
     private User user;
     private String role;

    public UserRole() {
    }

	
    public UserRole(User user) {
        this.user = user;
    }
    public UserRole(User user, String role) {
       this.user = user;
       this.role = role;
    }
   
    public Integer getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


