package app.model;
// Generated Jul 4, 2018 8:41:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String email;
     private String password;
     private String enable;
     private Set userRoles = new HashSet(0);

    public User() {
    }

	
    public User(String email, String password) {
        this.email = email;
        this.password = password;
    }
    public User(String email, String password, String enable, Set userRoles) {
       this.email = email;
       this.password = password;
       this.enable = enable;
       this.userRoles = userRoles;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEnable() {
        return this.enable;
    }
    
    public void setEnable(String enable) {
        this.enable = enable;
    }
    public Set getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set userRoles) {
        this.userRoles = userRoles;
    }

}


