package app.model;
// Generated Jul 4, 2018 8:41:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vivienda generated by hbm2java
 */
public class Vivienda  implements java.io.Serializable {


     private Integer idVivienda;
     private Direccion direccion;
     private Servicio servicio;
     private String esPropia;
     private String viveCon;
     private Set personas = new HashSet(0);

    public Vivienda() {
    }

    public Vivienda(Direccion direccion, Servicio servicio, String esPropia, String viveCon, Set personas) {
       this.direccion = direccion;
       this.servicio = servicio;
       this.esPropia = esPropia;
       this.viveCon = viveCon;
       this.personas = personas;
    }
   
    public Integer getIdVivienda() {
        return this.idVivienda;
    }
    
    public void setIdVivienda(Integer idVivienda) {
        this.idVivienda = idVivienda;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public String getEsPropia() {
        return this.esPropia;
    }
    
    public void setEsPropia(String esPropia) {
        this.esPropia = esPropia;
    }
    public String getViveCon() {
        return this.viveCon;
    }
    
    public void setViveCon(String viveCon) {
        this.viveCon = viveCon;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


